#! /bin/bash
# Purpose: A shell script to set up the project in one command
# Usage: . setup.sh

make requirements \
    && uv run pre-commit install \
    && uv run nbstripout --install \
    && uv run python3 -m ipykernel install \
    --user --name="{{ cookiecutter.repo_name }}" \
    && touch .env
