#! /bin/bash
# Purpose: A shell script to set up the project in one command
# Usage: . setup.sh

make environment \
    && source .venv/bin/activate \
    && make requirements \
    && pre-commit install \
    && nbstripout --install \
    && python3 -m ipykernel install \
    --user --name="{{ cookiecutter.repo_name }}" \
    && touch .env
